all: grafik office video web edu audio

grafik: grafik.tex
	lualatex -interaction=nonstopmode grafik.tex

office: office.tex
	lualatex -interaction=nonstopmode office.tex

video: video.tex
	lualatex -interaction=nonstopmode video.tex

web: web.tex
	lualatex -interaction=nonstopmode web.tex

edu: edu.tex
	lualatex -interaction=nonstopmode edu.tex

audio: audio.tex
	lualatex -interaction=nonstopmode audio.tex

clean:
	rm *.log *.aux *.out 
